# Generated by Django 4.0.5 on 2022-06-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appestudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
